# Generated by Django 3.2.16 on 2023-09-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_squashed_0011_auto_20230825_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Обязательное поле. Не более 150 символов.', max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, help_text='Необязательное поле. Не более 150 символов.', max_length=150, verbose_name='Фамилия')),
                ('login', models.CharField(help_text='Обязательное поле. Не более 150 символов.', max_length=150, verbose_name='Login')),
                ('email', models.EmailField(help_text='Обязательное поле. Не более 150 символов.', max_length=150, verbose_name='Email')),
            ],
        ),
    ]
